### PR TITLE
Handle non-ObjectID ids

### PR DESCRIPTION
**Pull request by Pugio**
Apologies for not creating a separate branch. ObjectIDs are always either 12 bytes or 24 hex characters; anything else is a custom ID and should be handled as such.

### CODE REVIEW

**Comment by louischatriot** [comment]
Thank you for the PR, makes things clearer. This problem is actually non trivial, due to the number of possible edge cases in MongoDB (design flaws imo). In your example, if you have a document `{ _id: "notanobjecti" }` in the DB, your code will try to create an `ObjectId("notanobjecti")` which will not work.

Also your id can be a number and not a string, so for example if you have a doc `{ _id: 42 }` (42 being a number not the string `"42"`), `req.params.id` will be a string so Mongo Edit won't find the document.

To make things even more difficult, you can have two different docs with ids `ObjectId("11111111111111111111aaaa")` and `11111111111111111111aaaa`. They look alike but one is an ObjectId and the other a string. And you can also have two different docs with ids `42` and `"42"`.

It is not possible to cover every imaginable case so we must decide on the most probable strategy. This will be hard to do with both of us so I'll start from this code and show you what I have in mind when it's done.

**Comment by Pugio** [comment]
Good points. What about annotating the ID field in the URL with the appropriate type information?

ie. routes/collection.js:82

``` javascript

      docs.forEach(function (doc) {
        contents.push({ doc: JSON.stringify(doc, undefined, 2)
                      , _id: typeof(doc._id)+':'+doc._id });
      });
```

lib/helpers.js

``` javascript
module.exports.idForRequestId = function (request_id) {
  var pieces = request_id.match(/^(.+?):(.+)$/);

  switch (pieces[1]) {  //type
    case 'number': return parseFloat(pieces[2]);
    case 'string': return pieces[2];
    case 'object': return ObjectID(pieces[2]);
  }
};
```

**Comment by louischatriot** [comment]
Good idea but it would make the urls complicated (and break the current ones). One of the most useful aspects of Mongo Edit (for my company anyway) is that you ca use the urls `/:collection/:id/edit` in your application and directly see the documents in mongo edit.

What I have in mind is an intelligent guess that works in all cases where the choice of ids is coherent (always of the same type) and  is not "stupid" (i.e. if you use `42` and `"42"` as different indexes you have bigger problems than mongo edit not working). What do you think ?

**Comment by Pugio** [comment]
Makes sense. So you'd query the index (or just collection.findOne()._id) for the ID type and assume all incoming IDs are of that type? I like it.

As you say, if it doesn't work you have bigger problems.

**Comment by louischatriot** [comment]
Here is the code I use, and it works in the "edit" view. I still need to test it and use it in other views and I'll merge this in master. Basically I test every time the route is called so I make up to 3 extra calls (no need to worry about performance for a DB GUI anyway) but only one in the most usual case (ObjectId). Don't hesitate if you think it could be done better !

``` javascript
/**
 * From a stringId, return an id that corresponds to an object in the DB (if possible)
 * We try to match these criteria, in order: ObjectId, string, number
 * If your DB uses its ids in a coherent way (e.g. only ObjectIds or only string)
 * this will always work. It may not work if you have two different ids with the same
 * string representation, e.g. 42 (number) and "42" (string). But if you do that I think
 * you should change your schema!
 *
 * @param {String} collectionName
 * @param {String} stringId String representation of the id we're looking for
 * @param {Function} callback Signature: err, id
 */
module.exports.getIdFromStringId = function (collectionName, stringId, callback) {
  // Try an id, stop execution if it works, continue looking if it doesn't
  function tryId(id, cb) {
    collection = db.collection(collectionName);
    collection.findOne({ _id: id }, function (err, doc) {
      if (!err && doc) {
        return callback(null, id);
      } else {
        return cb();
      }
    });
  }

  async.waterfall([
  function (cb) {   // Try ObjectId
    var id;
    try {
      id = new ObjectID(stringId);
    } catch (e) {
      return cb();
    }

    tryId(id, cb);
  }
  , async.apply(tryId, stringId)   // Try string
  , async.apply(tryId, parseInt(stringId, 10))   // Try number
  ], function () { return callback('No match found'); });
};
```

**Comment by Pugio** [comment]
It's more complicated than we thought, I think. An _id can be of any type from [here](http://docs.mongodb.org/manual/reference/operator/type/) except for Array. The following should handle most use cases, without the async callbacks.

``` javascript
module.exports.getIdFromStringId = function (collectionName, stringId, callback) {
    var doc = db.collection(collectionName).findOne({},{_id:1});
    var id  = doc._id;

    switch(typeof(id)) {
        case "number":
            return parseFloat(stringId);
        case "string":
            return stringId;
        case "object":
            if (id instanceof ObjectID)
                return ObjectID(stringId);
            if (id instanceof NumberLong)
                return NumberLong(stringid);
            return eval(stringId);
        case "boolean":
            return stringId === "true";
    }
}
```

Since we don't need any optimization, there's no need to clutter the code with creating an initial ObjectID (and it's try/catch) for the findOne().

**Comment by louischatriot** [comment]
Hello Pugio,

Sorry for not getting back to you earlier, I was swamped in work and also busy with two other big projects:  
- NeDB, a dependency-less, embedded database using the same API as MongoDB: https://github.com/louischatriot/nedb
- A continuous integration and deployment server: https://github.com/louischatriot/braindead-ci

So, I finally took the time to finish and merge this. I decided to go with my original method because there is no guarantee all _ids in a collection have the same type so we have to treat them on a case-by-case basis. Also, I only take care of the types ObjectId, string, interger and float.

I tried to tackle Dates but they are a pain and needed me to modify several parts of the code, and I think nobody uses Dates as their _ids. I also didn't tackle null, booleans and the other more exotic types because I don't think anybody uses them for their _ids.

If you have an idea to tackle Dates gracefully I'm all hears :)
Cheers,
Louis

**Pull request merged**
