### PR TITLE
Add relative path to config ?

### PR DESCRIPTION
**Pull request by pzeups**
Much better to host anywhere.

### CODE REVIEW

**Comment by louischatriot** [comment]
If I'm correct, the purpose is to use it not just from a domain but any root url i.e. http://example.com/mongo_edit_root/[MongoEdit_urls_here] ?

**Comment by pzeups** [comment]
No, because of http://example.com/mongoedit/active/5125499793f1deb40f000001/edit

have to load css and other stuffs in normal way which cannot be

http://example.com/mongoedit/active/5125499793f1deb40f000001/edit/bootstrap.css

 so "relative" path has to be '/mongoedit/' Maybe I should name it "absolute" ... with a url ? 

or find another solution by loading '../../../bootstrap.css' with a special layout for edit ?

**Comment by louischatriot** [comment]
Finally had time to merge this ... Several changes so that its compatible everywhere and uses the format I like for url prefixes (`/prefix`). It works well, you can test and tell me if anything goes wrong!

**Comment by lightjs** [comment]
Thx! That looks good :). "baseUrl" is a better name. I thought about it after > "relative" wasn't good.

**Pull request merged**
