### PR TITLE
fix not ObjectID _id

### PR DESCRIPTION
**Pull request by pzeups**

### CODE REVIEW

**Comment by louischatriot** [comment]
Thanks for that but I prefer to leave the page trigger an error instead. This url should not be called with a non objectId string anyway so I don't want to display an edit form if its the case.

The best would be to catch the error so that node doesnt crash and display the error message as it already happens.

**Comment by louischatriot** [comment]
I did it like this: https://github.com/tldrio/mongo-edit/commit/2e61e4d3c012ea3d00dcf10a6ecc6f3d703199ba

**Comment by lightjs** [comment]
Agreed, needs to fix another file anyway. (for the save function)

But what happens for the other kinds of Mongo ID? (I think to custom shard key for example)

**Comment by louischatriot** [comment]
Non standard mongo ids and custom shard keys are currently not supported (maybe they are but then it would be a coincidence !). My take is that if you need those, its possible you've outgrown the need for Mongo Edit. But if it's easily supportable that would be a great addition to Mongo Edit.

**Pull request closed without merging**
